# Generated by Django 5.2.3 on 2025-09-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('input_paceholder', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('he', 'Hebrew')], max_length=2)),
            ],
        ),
    ]
