# Generated by Django 5.2.3 on 2025-09-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headline',
            old_name='input_paceholder',
            new_name='input_placeholder',
        ),
    ]
