# Generated by Django 5.2.3 on 2025-09-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headline', '0002_rename_input_paceholder_headline_input_placeholder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headline',
            old_name='title',
            new_name='wellcome_message',
        ),
    ]
