# Generated by Django 5.2.3 on 2025-08-20 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0017_userprofile_google_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='google_profile_picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
